---
title: "p8105_hw6_zx2482"
author: "Allison Xia"
date: "2023-12-02"
output: github_document
---

```{r}
library(readr)
library(dplyr)
library(stringr)
```

```{r echo = FALSE}
# URL of the dataset
url <- "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

# Reading the dataset
homicide_data <- read_csv(url)

```
```{r}
# Create a city_state variable
homicide_data <- homicide_data %>%
  mutate(city_state = paste(city, state, sep = ", "))

# Create a binary variable for solved homicides
homicide_data <- homicide_data %>%
  mutate(solved_binary = ifelse(disposition == "Closed by arrest", 1, 0))

# Omit specified cities
homicide_data <- homicide_data %>%
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))) 

# Limit analysis to cases where victim_race is white or black
homicide_data <- homicide_data %>%
  filter(victim_race %in% c("White", "Black"))

# Ensure victim_age is numeric
homicide_data$victim_age <- as.numeric(homicide_data$victim_age)

# View the modified dataset
head(homicide_data)
```

```{r}
# Filter data for Baltimore, MD
baltimore_data <- homicide_data %>%
  filter(city_state == "Baltimore, MD")

# Fit logistic regression model
model <- glm(solved_binary ~ victim_age + victim_sex + victim_race, 
             data = baltimore_data, family = binomial())

# Extract adjusted odds ratio for male vs female victims
# Calculate OR confidence interval
model |> 
  broom::tidy() |> 
  mutate(
    OR = exp(estimate), 
    OR_CI_upper = exp(estimate + 1.96 * std.error),
    OR_CI_lower = exp(estimate - 1.96 * std.error)) |> 
  filter(term == "victim_sexMale") |> 
  select(OR, OR_CI_lower, OR_CI_upper) |>
  knitr::kable(digits = 3)
```

